### PR TITLE
#3207 Use Central Package Management (CPM) in CslaFastStart solution

### PR DESCRIPTION
**Pull request by sshushliapin**
Use Central Package Management (CPM) in CslaFastStart solution (#3207).

In order to unilize CPM, the .Net Framework solution has been upgraded to SDK project style. Target framework is left unchanged (net48).

### CODE REVIEW

**Comment by rockfordlhotka** [comment]
@sshushliapin please accept the invite to join the GitHub repo (should be in your email). That will allow me to assign the issue to you so other people know you are working on it.

**Comment by rockfordlhotka** [comment]
@sshushliapin also, please put the issue number in the commit messages, like this:

```
#xxxx Remove output type
```

This properly links the commits to the issue so it is easier to understand how the code has changed over time.

**Comment by sshushliapin** [comment]
> @sshushliapin please accept the invite to join the GitHub repo (should be in your email). That will allow me to assign the issue to you so other people know you are working on it.

@rockfordlhotka, I did it yesterday, accepted once again. Please let me know if it works now.

**Comment by rockfordlhotka** [comment]
> > @sshushliapin please accept the invite to join the GitHub repo (should be in your email). That will allow me to assign the issue to you so other people know you are working on it.
> 
> @rockfordlhotka, I did it yesterday, accepted once again. Please let me know if it works now.

It works now. Excellent!

**Comment by rockfordlhotka** [comment]
@sshushliapin these updates look great, thank you!

I wonder if we should update the project to net8.0, or leave it using .NET Framework? What do you think?

**Review by rockfordlhotka — APPROVED** [review]

**Comment by sshushliapin** [comment]
> I wonder if we should update the project to net8.0

Yep, sounds good to me. Will do now.

**Review by rockfordlhotka — APPROVED** [review]

**Pull request merged**
