### PR TITLE
Rename ServiceProviderScope to CurrentServiceProvider #1999

### LINKED ISSUE #1999: Rename ApplicationContext.ServiceProviderScope
**Is your feature request related to a problem? Please describe.**
Per this [discussion](https://github.com/MarimerLLC/csla/discussions/1991), rename ApplicationContext.ServiceProviderScope to something more intuitive.

Maybe ApplicationContext.CurrentServiceProvider?

### PR DESCRIPTION
**Pull request by ajj7060**
Rename ServiceProviderScope to CurrentServiceProvider 

Closes #1999

### CODE REVIEW

**Comment by rockfordlhotka** [comment]
Thank you @ajj7060, but I think you need to update a test:

```text
C:\projects\csla\Source\csla.netcore.test\DataPortal\ServiceProviderInvocationTests.cs(35,31): error CS0117: 'ApplicationContext' does not contain a definition for 'ServiceProviderScope' 
```

**Comment by ajj7060** [comment]
@rockfordlhotka Yeah I'm not sure how I missed that, I'll get it fixed.

**Comment by ajj7060** [comment]
@rockfordlhotka Should be fixed; looks like the test projects aren't in csla.build.sln (or they aren't set to build).  Should be fixed now.

**Comment by rockfordlhotka** [comment]
@ajj7060 the tests are in `csla.test.sln`, and that's the solution used by appveyor. The `csla.build.sln` is what's used to create the release, so it only builds release assets, in Release mode.

**Pull request merged**
