### PR TITLE
Added csla-github-flow-using-vs2019.md

### PR DESCRIPTION
**Pull request by russblair**
Added document "Git Flow for CSLA Development using VS2019".

### CODE REVIEW

**Comment by rockfordlhotka** [comment]
@russblair I accepted the PR because it looked ok - but it turns out that all the images were wiped out.

I'm going to revert the doc to its previous state (hopefully), and we'll have to try this again.

**Comment by rockfordlhotka** [comment]
@russblair hmm, my attempt to revert _also_ has no images. I'm not sure how to get them back 😢

**Comment by rockfordlhotka** [comment]
@russblair I think I figured out what is going on. This having images in a doc like you do is new to me.

What has worked in the past, is that images go into an `/images` subdirectory below the `.md` file location, and the `.md` file references the images. That way the images are explicitly part of the repo.

**Comment by russblair** [comment]
I originally created the document with an images folder and then discovered the ability to imbed the images. I tried the imbedded and discovered that the file size was not too large and I thought it was simpler. 1) Does it display correctly?  2) Would you prefer I use the images folder method?

**Comment by rockfordlhotka** [comment]
It does not display correctly, that's the problem - the images didn't survive the PR process apparently.

**Comment by russblair** [comment]
Ok. I will change back to the images folder and create a new PR.

**Comment by russblair** [comment]
I sent the md file with the imbedded images to your email yesterday. Does that md work properly?

**Pull request merged**
