### PR TITLE
Backporting 3633 to v7.x

### PR DESCRIPTION
**Pull request by tkyle**
[#3633](https://github.com/MarimerLLC/csla/issues/3633)

Backporting LocalProxy changes to v7.x so it's thread safe.

### CODE REVIEW

**Comment by rockfordlhotka** [comment]
@tkyle have you tested this against your code base?

**Comment by tkyle** [comment]
I have.

I tested it in our code base and it solved our issue.

I also had a demo application I created that reproduced the issue by creating multiple threads. This application was also fixed after I made the code change.

In the past we've had issues with CSLA, dependency injection / scoping, and connection leaks. After testing my code change I didn't notice any connection leaks.

Also, to test scoping, I added some test code to one of our connection factories and made sure that it wasn't just pulling the injected connection factory from the root container each time. This seemed to work as expected.

If you need me to perform additional testing I can, but I'd need you to tell me specifically what to look into.

**Comment by rockfordlhotka** [comment]
@tkyle am I right in remembering that you were doing the backport as a 2-part PR? As in there is another PR coming with more changes to complete the v7 solution?

**Comment by tkyle** [comment]
Well, we did discuss that. I thought about adding in the code for the async changes you guys made where it waits until all calls are done, but I opted to not worry about that for right now. I'm not sure that it would benefit us at this time.

After discussing it with my team lead we decided it was best / easiest to just see if this one change got us to where we needed to be, and hopefully we'll just be able to update our CSLA version again in the near future-ish and get the benefit of all the additional changes you guys have made without having to try and backport anything extra.

**Comment by rockfordlhotka** [comment]
OK, I will see if I can build the v7 codebase or not.

**Pull request merged**
