### PR TITLE
API Documentation Initial Release

### PR DESCRIPTION
**Pull request by Brannos1970**
This is the initial release of the API Documentation as per #2384.

### CODE REVIEW

**Comment by rockfordlhotka** [comment]
@Brannos1970 I had to revert this PR, because something got messed up with the generated index.md file - there was no resulting index.html at all from what I could find.

**Comment by Brannos1970** [comment]
@rockfordlhotka I don't know what happened, it was working on my fork. To fix I deleted my fork and created a new one then generated the documentation. After testing I don't see any issues. 

You can see the main index page in my fork at [https://brannos1970.github.io/csla/](https://brannos1970.github.io/csla/) and the generated API pages at [https://brannos1970.github.io/csla/5.4.2/html/]( https://brannos1970.github.io/csla/5.4.2/html/).

I am not changing the index page just in case it is something on my end I am not catching it. We can add the API link to it later.

If you are good with this I will try another push.

**Comment by rockfordlhotka** [comment]
Yeah, let's try another PR and see.

Is your testing running through the jekyll engine? That's what gh-pages does - when I update the repo they kick off a jekyll task to convert all the md files to html, and do whatever else they do.

**Comment by Brannos1970** [comment]
I had previously but I thought I had reversed it on my end. 

I will get the PR out to you.

**Pull request merged**
