### PR TITLE
use some auto properties

### PR DESCRIPTION
**Pull request by SimonCropp**

### CODE REVIEW

**Comment by rockfordlhotka** [comment]
@SimonCropp wow, this is the sort of code cleanup I've just never had time to do - you've touched files that haven't been edited in years! Nice.

There's a merge conflict that needs to be resolved before this PR can be accepted.

**Comment by SimonCropp** [comment]
conflicts resolved

**Comment by rockfordlhotka** [comment]
@SimonCropp now if it only built 😄 

btw, thank you so much for all these great contributions!

**Comment by SimonCropp** [comment]
> now if it only built 

damn. sorry. juggling too many things this morning. will fix

**Pull request merged**
