### PR TITLE
Fix Blazor authentication error

### LINKED ISSUE #3890: Do not call GetAuthenticationStateAsync outside of the DI scope for a Razor component
A change in CSLA from 8.0.0 to 8.0.1 appears to have caused an issue with authentication: "Do not call GetAuthenticationStateAsync outside of the DI scope for a Razor component"

Described in #3815

### PR DESCRIPTION
**Pull request by rockfordlhotka**
Fixes #3890

### CODE REVIEW

**Comment by swegele** [comment]
We are doubling up here on a two items [from this change](https://github.com/MarimerLLC/csla/pull/3903/files).  Not sure how to handle that?

**Comment by StefanOssendorf** [comment]
> We are doubling up here on a two items [from this change](https://github.com/MarimerLLC/csla/pull/3903/files). Not sure how to handle that?

I think he'll get a merge conflict 😆

**Comment by rockfordlhotka** [comment]
If the PR from @swegele already fixes this then we can just close this one and discard it. I didn't realize you'd fixed this issue in the other PR.

**Comment by swegele** [comment]
What about the few changes you had here to make the `BlazorExample` pages work?

**Comment by rockfordlhotka** [comment]
> What about the few changes you had here to make the `BlazorExample` pages work?

I'll have to redo those as part of another PR - there's an issue in the backlog to update the samples for CSLA 9.

**Pull request closed without merging**
