### PR TITLE
Csla.Windows for .NetCore3 - Add project and nuspec definition

### PR DESCRIPTION
**Pull request by GillesBer**
#1234  I can't compile nor create iOS and Android nuspect from my computer
I changed the AssemblyInfo.cs as an hybrid between NetCore2 and Net46 templates
I choose to set the TargetFramework (NetCoreApp3.0) in the project name to be consistent with other project.

Ps: my first PR!

### CODE REVIEW

**Comment by GillesBer** [comment]
> Are there dependencies for the .NET Core 3 Windows Forms version? 
I did not explicetely add any dependency.
But there is a 'magic' flag in the project:   <UseWindowsForms>true</UseWindowsForms>

**Comment by GillesBer** [comment]
I need to fix the NuSpec definition. I will do it tomorrow.

**Comment by rockfordlhotka** [comment]
Once it works in v5 I'm open to creating a 4.12.0 if it can be backported.

**Comment by GillesBer** [comment]
The last commit should have fixed the NuSpec definition.

**Comment by rockfordlhotka** [comment]
Congratulations on your first PR @GillesBer 🥇

**Pull request merged**
