### PR TITLE
Prevent use of .. or : in file path

### LINKED ISSUE #3551: Prevent the use of ../ when loading assemblies
During deserialization it is possible to provide a path for a target assembly. This path shouldn't allow "../" to avoid loading an assembly from outside the directory structure containing the actual business app (such as /bin/**).

As per a Discord conversation with @pizzeys (mopman)

https://github.com/MarimerLLC/csla/blob/ca11ad091f42e59b7324ea86fc0080f1d55b876d/Source/Csla/Reflection/MethodCaller.cs#L255

### PR DESCRIPTION
**Pull request by rockfordlhotka**
Closes #3551

### CODE REVIEW

**Review by BaHXeLiSiHg — COMMENTED** [review]
Yep, I'm okay with that.

**Comment by rockfordlhotka** [comment]
I've never explored that concept @sampizzey, would this be in GH or NuGet?

**Comment by ajohnstone-ks** [comment]
@rockfordlhotka I just got an email b/c one of my repo's is apparently using a version of Csla which is vunerable.

https://cve.mitre.org/cgi-bin/cvename.cgi?name=2024-28698

Was this fix ever backported?  It seems like it should be given the effort required to move to Csla 6+.

**Comment by rockfordlhotka** [comment]
> @rockfordlhotka I just got an email b/c one of my repo's is apparently using a version of Csla which is vunerable.
> 
> https://cve.mitre.org/cgi-bin/cvename.cgi?name=2024-28698
> 
> Was this fix ever backported? It seems like it should be given the effort required to move to Csla 6+.

https://github.com/MarimerLLC/csla/issues/4133

**Pull request merged**
