### PR TITLE
Correction to CslaValidator to resolve issue #1436

### PR DESCRIPTION
**Pull request by TheCakeMonster**
Small change to CslaValidator to make it respect business rule severities. The original version of my code considered all broken rules to be validation failures. After this update, only broken rules with severities of Error are considered validation failures which should prevent form submission.

Also includes some extra unit tests and fixes to existing tests which were not exercising the correct part of the codebase. There is also localisation of one final exception message that was missed in a previous PR.

Resolves defect identified in issue #1436

### CODE REVIEW

**Comment by rockfordlhotka** [comment]
@TheCakeMonster it looks like there were some dependency versioning issues. I have accepted a different PR that should fix them, so hopefully if you re-pull and merge master into your PR it'll fix the build issue.

**Comment by TheCakeMonster** [comment]
@rockfordlhotka I think I've done what you suggested, but it appears to have made no difference. It appears that the unit tests are failing on the build server, despite all of them passing on my local machine.

I tried upgrading the tests project to .NET Core 3.1 in case that helped, but it continues to fail.

Just at the moment, I'm a bit stumped as to what the problem might be.

**Comment by TheCakeMonster** [comment]
@rockfordlhotka I've been researching AppVeyor unit test failures and it's sparked a thought: do CSLA business rules run asynchronously now? I'm wondering whether the failures could be triggered by a timing issue, or something - but I am clutching at straws.

I can't get the tests to fail locally, and a lack of an ability to reproduce the problem in conjunction with limited knowledge of AppVeyor makes it hard to resolve.

**Comment by TheCakeMonster** [comment]
Aha! Sorted it. 

It took a while to come up with a relatively simple idea, but I eventually twigged that I could use the console output from AppVeyor to output additional debug information to help me identify the problem.

It looks like the problem was caused by a missing resources entry for the MinLength rule. I'm not sure what culture AppVeyor builds would occur under, but there's something missing for whatever culture it is, and that causes the rule to fail, even though the rule conditions are met.

Never seen that before.

Sorry for the delay. I hope you don't pay per build!

**Comment by rockfordlhotka** [comment]
Wow @TheCakeMonster - thank you for your dedication to solving the build issue!

(fortunately appveyor is free for open source projects)

**Pull request merged**
