### PR TITLE
Added DisplayIndex Property to Business Rules

### LINKED ISSUE #3225: Add DisplayIndex property to business rules
How about adding a property 'order' to BusinessRule?
Something similar to tab index in UI. It would be easier for users to relate broken business rules to UI components.

_Originally posted by @Chicagoan2016 in https://github.com/MarimerLLC/csla/discussions/3223_

### PR DESCRIPTION
**Pull request by Freelancingonupwork**
This adds the new Property DisplayIndex in this Class `BusinessRule`.

Fixes #3225

### CODE REVIEW

**Comment by StefanOssendorf** [comment]
Hi and thanks for your contribution.
Please make sure to send rocky a signed contribution agreement. If you've already send it please be patient since rocky is currently on the road and it could take some time. Thanks again :)

**Review by StefanOssendorf — CHANGES_REQUESTED** [review]
Hi. The PR in general looks good to me. But please add some test so verify the DisplayIndex is correctly propagated through the rule engine to the broken rules output. Thanks in advance.

**Comment by Freelancingonupwork** [comment]
Hi. Thank you for the input. 
I have added test `BusinessRuleDisplayIndex`  to verify the DisplayIndex is correctly propagated through the rule engine to the broken rules output.

**Comment by rockfordlhotka** [comment]
@Freelancingonupwork I don't have a contribution agreement from you (or it went to spam). Have you sent me the signed document?

**Comment by rockfordlhotka** [comment]
> > @Freelancingonupwork I don't have a contribution agreement from you (or it went to spam). Have you sent me the signed document?"
> 
> I have sent signed document

You should have an email with an invite to this GitHub repo.

**Comment by Freelancingonupwork** [comment]
> > > @Freelancingonupwork I don't have a contribution agreement from you (or it went to spam). Have you sent me the signed document?"
> > 
> > 
> > I have sent signed document
> 
> You should have an email with an invite to this GitHub repo.



> > > @Freelancingonupwork I don't have a contribution agreement from you (or it went to spam). Have you sent me the signed document?"
> > 
> > 
> > I have sent signed document
> 
> You should have an email with an invite to this GitHub repo.

I have accepted the invite  now.- I have already send the doc from the same email  from which I have been invited. thanks

**Comment by rockfordlhotka** [comment]
Thank you @Freelancingonupwork. Once @StefanOssendorf is happy with your changes we should be good.

**Review by StefanOssendorf — APPROVED** [review]

**Comment by StefanOssendorf** [comment]
Thank you for your contribution :)

**Pull request merged**
