### PR TITLE
Add pdb files to nuspec

### LINKED ISSUE #1997: Csla.pdb missing in 5.4.0 nuget package
I have a .NET Core 3.1 app which is using CSLA version 5.3.1. I have upgraded to the latest version on nuget, 5.4.0.

Now when I run the app I get the error below:
image

I'm not 100% sure if the module version is correct as its showing `5.04.0.0` rather than `5.4.0.0` as it is on the dll in the `bin` folder.
image

Our .NET Core 3.1 app is an API using ServiceStack.

The code CSLA code it first hits is the below code which works on 5.3.1 but not 5.4.0.

Our ServiceStack API validation calls a static ProductChecker helper class
```
            if (!await ProductChecker.ExistsAsync(criteria.ProductId))
            {
                throw new HttpError(System.Net.HttpStatusCode.NotFound, $"Product Id: {criteria.ProductId} not found");
            }
```

ProductChecker static helper class
```
    [Serializable]
    public static class ProductChecker
    {
        public static async Task<bool> ExistsAsync(int productId)
        {
            var cmd = await DataPortal.CreateAsync<ProductExistsCommand>();
            cmd.ProductId = productId;
            cmd = await DataPortal.ExecuteAsync(cmd);
            return cmd.ProductExists;
        }
    }
```
ProductExistsCommand CSLA command used in the ProductChecker
```
    [Serializable]
    public class ProductExistsCommand : CommandBase<ProductExistsCommand>
    {
        public ProductExistsCommand() { }

        public ProductExistsCommand(int productId)
        {
            ProductId = productId;
        }

        public static readonly PropertyInfo<int> ProductIdProperty = RegisterProperty<int>(c => c.ProductId);
        public int ProductId
        {
            get { return ReadProperty(ProductIdProperty); }
            set { LoadProperty(ProductIdProperty, value); }
        }

        public static readonly PropertyInfo<bool> ProductExistsProperty = RegisterProperty<bool>(c => c.ProductExists);
        public bool ProductExists
        {
            get { return ReadProperty(ProductExistsProperty); }
            private set { LoadProperty(ProductExistsProperty, value); }
        }

        [Create, RunLocal]
        private void Create() { }

        [Execute]
        protected void Execute([Inject] IProductRepository dal)
        {
            ProductExists = dal.Exists(x => x.ProductId == ProductId); //calls SQL database using an ORMLite query.
        }
    }
```

### PR DESCRIPTION
**Pull request by adrianwright109**
Fixes #1997

I believe the `netstandard2.0` and `net5.0` were missing entries in the `.nuspec` file that will include the *.pdb files.

Updated `Core.NuSpec`.

N.B. I need to sign the contributor agreement.

### CODE REVIEW

**Comment by rockfordlhotka** [comment]
@adrianwright109 thank you for the PR! Can you send the contributor agreement?

**Comment by rockfordlhotka** [comment]
@adrianwright109 let me know when you feel this is complete, thank you!

**Comment by adrianwright109** [comment]
@rockfordlhotka - This is now ready.  I have tested the `.\NuGet\Build All.ps1` and `.\NuGet\Push All.ps1` PowerShell scripts that they build and push the symbols to nuget (I pointed them to my own nuget unlisted) and now show that symbols are available to download as this screenshot shows:

image

**Comment by rockfordlhotka** [comment]
Wonderful, thank you!

**Pull request merged**
