### PR TITLE
Enhance WPF ProjectTracker app configuration

### PR DESCRIPTION
**Pull request by BlagoCuljak**
My first CSLA Pull request
#1542

### CODE REVIEW

**Comment by rockfordlhotka** [comment]
Thank you @BlagoCuljak 

It seems like the configuration extension method applies to all platforms right? Perhaps it should go into the `Csla.Shared` project in the `Csla.Configuration` namespace.

What do you think?

**Comment by BlagoCuljak** [comment]
Sure, that can be in Shared. I will make another pull request, sorry.

**Comment by BlagoCuljak** [comment]
@rockfordlhotka I trying to do the same for Blazor projects, but Client and Server are not referenced to ProjectTracker.BusinessLibrary.Shared. Can I reference them to use configuration extension? Is that ok?

**Comment by rockfordlhotka** [comment]
Blazor projects work differently, in that the `AddCsla` and `UseCsla` methods are used in `Startup.cs` or `Program.cs` (in the new client-side approach).

fwiw, I've started using the newer approach for my WPF and WinForms apps too. It is a little extra work to set up a builder and service collection, but worth it to get DI and all the other new goodness.

I approve and appreciate your new method because not everyone will want to use the new goodness in .NET. But for my part, I plan to use the new approach for ProjectTracker as I update everything for the books (which takes months - writing books isn't fast!).

**Comment by BlagoCuljak** [comment]
Sure man, glad I could help!

**Comment by rockfordlhotka** [comment]
btw, you don't need to do _another_ PR - you can just update this one.

**Comment by rockfordlhotka** [comment]
@BlagoCuljak Are you still planning to update this PR to add that extension method to `Csla.Configuration`?

**Comment by BlagoCuljak** [comment]
I have a question, ProjectTracker uses the [ProjectTracker.BusinessLibrary.Netstandard](https://github.com/MarimerLLC/csla/tree/master/Samples/ProjectTracker/ProjectTracker.BusinessLibrary.Netstandard) for objects, least in my Visual Studio. The Shared folder is unloaded, and not referenced in WpfUI.

**Comment by rockfordlhotka** [comment]
Shared projects are just containers for code. So the `ProjectTracker.BusinessLibrary.Netstandard` project references the shared project to get the code. The shared project itself doesn't get compiled, doesn't generate a DLL, nothing. That code is compiled by a concrete project like the `Netstandard` one.

So other projects reference the concrete project that actually does compile the code into an assembly.

**Comment by rockfordlhotka** [comment]
@BlagoCuljak I would like to get a contributor agreement from you - can you sign and send me that document?

**Comment by BlagoCuljak** [comment]
Sure, no problem. Do you need it for this task or in general?

I'm Central European Time, and on Easter Holiday by middle of next week.

**Comment by BlagoCuljak** [comment]
I know how shared projects work, but my issue is when I add file to Shared Project, it doesnt show up in BusinessLibrary, nor I can use it from WPF. 

If I add file to BusinessLibrary, then I can use it in other projects.

**Comment by rockfordlhotka** [comment]
I'm reviewing the ProjectTracker solution, and I see that I did move all the code from the shared project to the netstandard project, so the shared project is no longer needed. I'll remove it from the repo.

**Pull request closed without merging**
